### ISSUE TITLE
Invalidate Bad Data

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-terminal-app#37]
Get with Jonny Gartner on this. Whenever he scans his card, it scans around 14 digits. This is incorrect. 

This is because there is another RFID card in his wallet. This for some reason also does not submit a `\n` at the end.

A proposed solution to this: whenever the first character is entered, time for 0.5s after and automatically submit.

**Comment by SebastianNeiswanger** [comment]
Added a check for id of length 5. Still needs more work to make sure that we don't lose multiple people from a bad scan.
