### ISSUE TITLE
Implement the New Backend API for the Terminal App

### ISSUE THREAD

**Issue by SpBills** [CreativeSolutionsGroup/smart-events-terminal-app#49]
Tied very closely and maybe synonymous with https://github.com/CreativeSolutionsGroup/smart-events-terminal-app/issues/50

Also, please in this story have the terminal app send the things instantly THEN 30 seconds later rather than waiting 30 seconds from start.

**Comment by SpBills** [comment]
Just do the latter part here.

**Comment by ashlyndevries** [comment]
Already addressed.
