### ISSUE TITLE
SPIKE: research scanner speed

### ISSUE THREAD

**Issue by ian-harrington25** [CreativeSolutionsGroup/smart-events-terminal-app#6]

**Comment by Konolo** [comment]
specifications for the Omnikey scanners 

https://www.hidglobal.com/products/readers/omnikey/5427

**Comment by SpBills** [comment]
Need to ask IT about this.

**Comment by SpBills** [comment]
Looks like IT doesn't even know. Sad day. Will have to figure out what to do for this later.
