### ISSUE TITLE
Table structure for Locations

### ISSUE THREAD

**Issue by Konolo** [CreativeSolutionsGroup/smart-events-terminal-app#9]

**Comment by remfsv** [comment]
![Image](https://user-images.githubusercontent.com/67124816/185231185-d1d4dcec-5e35-49ca-ba24-5afd268ec314.png)

Location Table is still to be determined

**Comment by remfsv** [comment]
![Image](https://user-images.githubusercontent.com/67124816/185422929-d74460d1-bbe9-4e15-a6ef-a63672ebb15b.PNG)

We will no longer need the location aspect added.

**Comment by remfsv** [comment]
rpi_name was changed to alias

![Image](https://user-images.githubusercontent.com/67124816/185425059-86ac3f7e-4240-4723-8632-19c4f618ac2a.PNG)

**Comment by SpBills** [comment]
Reminder that this is how the DATABASE is laid out, not how the data is laid out when sent to the backend.

When sent to the backend, we are sending the RPI's mac address and student ID.

This will then look up the mac address associated with the RPI's mac address and thus the event with it.

It will then log it in the database for a checkin.
